apiVersion: 1
datasources:
  - name: TimescaleDB
    type: grafana-postgresql-datasource
    uid: timescaledb-ds
    url: timescaledb_live:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: $PG_PASSWORD
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    editable: true
